# Generated by Django 4.0 on 2021-12-24 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_student',
        ),
        migrations.AddField(
            model_name='customuser',
            name='userbirthday',
            field=models.DateField(null=True),
        ),
    ]
