# Generated by Django 4.0 on 2021-12-24 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_customuser_is_student_customuser_userbirthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userbirthday',
            new_name='user_birthday',
        ),
    ]
