# Generated by Django 4.0 on 2021-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategorySinglePlayer', models.BooleanField()),
                ('CategoryMultiplayer', models.BooleanField()),
                ('CategoryCoop', models.BooleanField()),
                ('CategoryMMO', models.BooleanField()),
                ('CategoryInAppPurchase', models.BooleanField()),
                ('CategoryIncludeLevelEditor', models.BooleanField()),
                ('CategoryVRSupport', models.BooleanField()),
                ('GenreIsIndie', models.BooleanField()),
                ('GenreIsAction', models.BooleanField()),
                ('GenreIsAdventure', models.BooleanField()),
                ('GenreIsCasual', models.BooleanField()),
                ('GenreIsStrategy', models.BooleanField()),
                ('GenreIsRPG', models.BooleanField()),
                ('GenreIsSimulation', models.BooleanField()),
                ('GenreIsEarlyAcces', models.BooleanField()),
                ('GenreIsFreeToPlay', models.BooleanField()),
                ('GenreIsSports', models.BooleanField()),
                ('GenreIsRacing', models.BooleanField()),
                ('GenreIsMassivelyMultiplayer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('GameName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GamesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReleaseDate', models.DateTimeField()),
                ('RequiredAge', models.IntegerField()),
                ('DemoCount', models.IntegerField()),
                ('DLCCount', models.IntegerField()),
                ('Metacritic', models.IntegerField()),
                ('RecommendationCount', models.IntegerField()),
                ('AboutText', models.CharField(max_length=400)),
                ('DetailedDescrip', models.CharField(max_length=800)),
                ('SupportedLanguages', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Windows', models.BooleanField()),
                ('Linux', models.BooleanField()),
                ('Mac', models.BooleanField()),
                ('PS4', models.BooleanField()),
                ('PS5', models.BooleanField()),
                ('XBOXONE', models.BooleanField()),
            ],
        ),
    ]
