# Generated by Django 4.0 on 2021-12-24 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('GameId', models.AutoField(primary_key=True, serialize=False)),
                ('GameName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsersFavorites',
            fields=[
                ('favoritesId', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games')),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Windows', models.BooleanField()),
                ('Linux', models.BooleanField()),
                ('Mac', models.BooleanField()),
                ('PS4', models.BooleanField()),
                ('PS5', models.BooleanField()),
                ('XBOXONE', models.BooleanField()),
                ('games', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games')),
            ],
        ),
        migrations.CreateModel(
            name='GamesDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ReleaseDate', models.DateField()),
                ('RequiredAge', models.IntegerField()),
                ('DemoCount', models.IntegerField()),
                ('DLCCount', models.IntegerField()),
                ('Metacritic', models.IntegerField()),
                ('RecommendationCount', models.IntegerField()),
                ('AboutText', models.CharField(max_length=400)),
                ('DetailedDescrip', models.CharField(max_length=800)),
                ('SupportedLanguages', models.CharField(max_length=250)),
                ('games', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategorySinglePlayer', models.BooleanField()),
                ('CategoryMultiplayer', models.BooleanField()),
                ('CategoryCoop', models.BooleanField()),
                ('CategoryMMO', models.BooleanField()),
                ('CategoryInAppPurchase', models.BooleanField()),
                ('CategoryIncludeLevelEditor', models.BooleanField()),
                ('CategoryVRSupport', models.BooleanField()),
                ('GenreIsIndie', models.BooleanField()),
                ('GenreIsAction', models.BooleanField()),
                ('GenreIsAdventure', models.BooleanField()),
                ('GenreIsCasual', models.BooleanField()),
                ('GenreIsStrategy', models.BooleanField()),
                ('GenreIsRPG', models.BooleanField()),
                ('GenreIsSimulation', models.BooleanField()),
                ('GenreIsEarlyAcces', models.BooleanField()),
                ('GenreIsFreeToPlay', models.BooleanField()),
                ('GenreIsSports', models.BooleanField()),
                ('GenreIsRacing', models.BooleanField()),
                ('GenreIsMassivelyMultiplayer', models.BooleanField()),
                ('games', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games')),
            ],
        ),
    ]
