# Generated by Django 4.0 on 2021-12-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_category_games'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesdetails',
            name='games',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games'),
        ),
        migrations.AlterField(
            model_name='gamesdetails',
            name='ReleaseDate',
            field=models.DateField(),
        ),
    ]
