# Generated by Django 4.0 on 2021-12-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=32)),
                ('UserPassword', models.CharField(max_length=32)),
                ('UserBirthday', models.DateTimeField(max_length=32)),
                ('UserEmail', models.EmailField(max_length=254)),
            ],
        ),
    ]
