# Generated by Django 4.0 on 2021-12-18 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='UserBirthday',
            field=models.DateField(max_length=32),
        ),
    ]
