# Generated by Django 4.0 on 2021-12-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_gamesdetails_games_alter_gamesdetails_releasedate'),
        ('user', '0002_alter_users_userbirthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFavorites',
            fields=[
                ('favoritesId', models.AutoField(primary_key=True, serialize=False)),
                ('games', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='game.games')),
                ('users', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.users')),
            ],
        ),
    ]
